version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "[$(date)] the time now !!!!!!!!!!!"
      - echo Installing dependencies... ... .... ....
      - npm ci --legacy-peer-deps
  pre_build:
    commands:
      - echo Running tests... ... .... ....
      - npm run test
  build:
    commands:
      - echo Building the application... .... .... ....
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no
